spring:
  rabbitmq:
    host: 10.178.0.9
    username: fwalkermq
    password: dpvmdnjzj!53@
    port: 5672
  data:
    elasticsearch:
      host: 10.146.0.3,10.146.0.3,10.146.0.4,10.146.0.4
      port: 9200
