spring:
  rabbitmq:
    #host: 10.146.0.2
    host: 10.178.0.10
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.5,10.146.0.6
      port: 9200