spring:
  datasource:
    url: jdbc:postgresql://10.140.0.2:5432/postgresql
#    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.146.0.2
    username: fwalkermq
    password: dpvmdnjzj!53@
    port: 5672
